export type ActivityTypeId = 'laser_clinic' | 'appointment_clinic' | 'salon' | 'other';

export interface ActivityType {
  id: ActivityTypeId;
  icon: string;
  titleKey: string;
  descriptionKey: string;
  featureKeys: string[];
}

export const ACTIVITY_TYPES: ActivityType[] = [
  {
    id: 'laser_clinic',
    icon: 'pi pi-heart',
    titleKey: 'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.LASER_CLINIC.TITLE',
    descriptionKey: 'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.LASER_CLINIC.DESCRIPTION',
    featureKeys: [
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.LASER_CLINIC.FEATURES.PACKAGES',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.LASER_CLINIC.FEATURES.DISCOUNTS',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.LASER_CLINIC.FEATURES.REPORTS',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.LASER_CLINIC.FEATURES.POS',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.LASER_CLINIC.FEATURES.SUBSCRIPTION',
    ],
  },
  {
    id: 'appointment_clinic',
    icon: 'pi pi-calendar',
    titleKey: 'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.APPOINTMENT_CLINIC.TITLE',
    descriptionKey: 'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.APPOINTMENT_CLINIC.DESCRIPTION',
    featureKeys: [
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.APPOINTMENT_CLINIC.FEATURES.BOOKINGS',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.APPOINTMENT_CLINIC.FEATURES.CALENDAR',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.APPOINTMENT_CLINIC.FEATURES.REMINDERS',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.APPOINTMENT_CLINIC.FEATURES.REPORTS',
    ],
  },
  {
    id: 'salon',
    icon: 'pi pi-palette',
    titleKey: 'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.SALON.TITLE',
    descriptionKey: 'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.SALON.DESCRIPTION',
    featureKeys: [
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.SALON.FEATURES.BOOKINGS',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.SALON.FEATURES.STAFF',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.SALON.FEATURES.PACKAGES',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.SALON.FEATURES.REPORTS',
    ],
  },
  {
    id: 'other',
    icon: 'pi pi-th-large',
    titleKey: 'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.OTHER.TITLE',
    descriptionKey: 'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.OTHER.DESCRIPTION',
    featureKeys: [
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.OTHER.FEATURES.CUSTOM',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.OTHER.FEATURES.FLEXIBLE',
      'ONBOARDING.BUSINESS_SETUP.ACTIVITY_TYPES.OTHER.FEATURES.REPORTS',
    ],
  },
];
